### ISSUE TITLE
Snagit EA

### ISSUE THREAD

**Issue by johnfgraphia** [Vanbella/Scripts#1]
================================================================================
Sep 12, 2018 at 3:26:25 PM
untitled text 5
--------------------------------------------------------------------------------
<result>Not Installed</result>
untitled text 5: line 13: [: /Applications/Snagit: binary operator expected

if [ -e $tgt ]; then
should probably be
if [[ -e $tgt ]]; then

================================================================================
Sep 12, 2018 at 3:27:38 PM
untitled text 5
--------------------------------------------------------------------------------
<result>2018.2.1</result>

**Comment by Vanbella** [comment]
Sep 12, 2018 at 4:31:28 PM
untitled text 2
--------------------------------------------------------------------------------
<result>2018.2.1</result>

**Comment by Vanbella** [comment]
Sep 12, 2018, 4:34:36 PM
untitled text 5
--------------------------------------------------------------------------------
<result>Not Installed</result>

**Comment by Vanbella** [comment]
fixed the issue
